### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/libxslt-feedstock#1]
@patricksnape, @msarahan, and @gillins is `libxslt` a low hanging fruit or is it too complicate that it is not worth the effort? Any advice is welcomed!

We already have `libxml2` but we need `libxslt` to build `lxml` on Windows.

**Comment by gillins** [comment]
It doesn't look too bad. See #2

**Comment by ocefpaf** [comment]
Thanks @gillins!

PS: I am testing bash on Windows 10 lately and that looks really promising.

**Comment by ocefpaf** [comment]
Done in #2
