### ISSUE TITLE
Missing dependency on icu

### ISSUE THREAD

**Issue by QuLogic** [conda-forge/libxslt-feedstock#8]
See conda-forge/lxml-feedstock#10 for original report. From there, we can see:
```
$ objdump -p libxslt.so.1 | grep NEEDED
  NEEDED               libxml2.so.2
  NEEDED               libz.so.1
  NEEDED               liblzma.so.5
  NEEDED               libiconv.so.2
  NEEDED               libicui18n.so.58
  NEEDED               libicuuc.so.58
  NEEDED               libicudata.so.58
  NEEDED               libm.so.6
  NEEDED               libdl.so.2
  NEEDED               librt.so.1
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
$ objdump -p libexslt.so.0 | grep NEEDED
  NEEDED               libxslt.so.1
  NEEDED               libxml2.so.2
  NEEDED               libz.so.1
  NEEDED               liblzma.so.5
  NEEDED               libiconv.so.2
  NEEDED               libicui18n.so.58
  NEEDED               libicuuc.so.58
  NEEDED               libicudata.so.58
  NEEDED               libm.so.6
  NEEDED               libdl.so.2
  NEEDED               librt.so.1
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
```
which shows that libxslt requires libicu, but this is not in the build info. I guess the assumption is that it comes from libxml2, but since icu is a direct dependency, it should be required here as well.

**Comment by ocefpaf** [comment]
@QuLogic `icu` is an optional dependency for `libxml2` and not a direct dependency of `libxslt`. But you are correct, it will link and as for its presence... In theory `conda` channel preference should take care of that, but since we cannot control how users install the their software we do over-specify dependencies, like you suggest, to ensure stability.

Do you mind sending a PR to fix that?

**Comment by QuLogic** [comment]
You're right that `libxslt` does not use `icu` directly. It turns out that it uses `xml2-config` to find linking arguments for `libxml2`, but this has no concept of the difference between static and shared libraries so it spits out the whole linkage even though it's unnecessary with shared libraries.

Even still, if you fix `libxslt` to prefer `pkg-config` instead (which differentiates between the shared/static deps), it _still_ links to `icu` because of the libtool archive. So yet another reason why conda-forge should not have shipped them.

**Comment by asmeurer** [comment]
```
$conda inspect linkages libxslt
libxslt
-------

icu-58.1-1:
    libicudata.58.dylib (lib/libicudata.58.dylib)
    libicui18n.58.dylib (lib/libicui18n.58.dylib)
    libicuuc.58.dylib (lib/libicuuc.58.dylib)

libiconv-1.14-4:
    libiconv.2.dylib (lib/libiconv.2.dylib)

libxml2-2.9.4-0:
    libxml2.2.dylib (lib/libxml2.2.dylib)

libxslt-1.1.29-3:
    libexslt.0.dylib (lib/libexslt.0.dylib)
    libxslt.1.dylib (lib/libxslt.1.dylib)

xz-5.2.2-0:
    liblzma.5.dylib (lib/liblzma.5.dylib)

zlib-1.2.11-0:
    libz.1.dylib (lib/libz.1.dylib)

system:
    libSystem.B.dylib (/usr/lib/libSystem.B.dylib)

not found:
```

So it links against it. Hence it should depend on it. The dependency also needs to be versioned (see https://github.com/conda-forge/lxml-feedstock/issues/14).

**Comment by QuLogic** [comment]
While that's true, it _shouldn't_. It's only because of libtool brokenness that it does. The correct fix is to stop shipping libtool archives as I've always advocated.
